name: moshtryate_new
description: Moshtryate new design

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider: ^4.3.3
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_facebook_auth: ^3.4.1
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.0.4
  share_plus: ^2.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/icons/icons8-almond-butter-48.png
    - images/icons/icons8-butter-16.png
    - images/icons/icons8-happy-64.png
    - images/icons/icons8-honey-48.png
    - images/icons/icons8-olive-oil-48.png
    - images/icons/icons8-olive-oil-100.png
    - images/icons/icons8-pizza-48.png
    - images/icons/icons8-spice-16.png
    - images/icons/icons8-teapot-50.png
    - images/icons/Bread&Bakeing/icons8-bread-48.png
    - images/icons/Bread&Bakeing/icons8-bread-64.png
    - images/icons/DiarayEggs/icons8-cheese-100.png
    - images/icons/DiarayEggs/icons8-egg-carton-48.png
    - images/icons/DiarayEggs/icons8-egg-carton-64.png
    - images/icons/DiarayEggs/icons8-milk-48.png
    - images/icons/DiarayEggs/icons8-milk-carton-64.png
    - images/icons/Drinkes/icons8-coffee-beans-50.png
    - images/icons/Drinkes/icons8-tea-64.png
    - images/icons/Drinkes/icons8-tea-100.png
    - images/icons/FruitsVegeies/icons8-apple-48.png
    - images/icons/FruitsVegeies/icons8-avocado-48.png
    - images/icons/FruitsVegeies/icons8-banana-48.png
    - images/icons/FruitsVegeies/icons8-cabbage-48.png
    - images/icons/FruitsVegeies/icons8-carrot-48 (1).png
    - images/icons/FruitsVegeies/icons8-cauliflower-48.png
    - images/icons/FruitsVegeies/icons8-chili-pepper-64.png
    - images/icons/FruitsVegeies/icons8-citrus-48.png
    - images/icons/FruitsVegeies/icons8-cucumber-48.png
    - images/icons/FruitsVegeies/icons8-eggplant-48.png
    - images/icons/FruitsVegeies/icons8-garlic-48.png
    - images/icons/FruitsVegeies/icons8-garlic-64.png
    - images/icons/FruitsVegeies/icons8-half-orange-48.png
    - images/icons/FruitsVegeies/icons8-lettuce-48.png
    - images/icons/FruitsVegeies/icons8-mango-48.png
    - images/icons/FruitsVegeies/icons8-onion-48.png
    - images/icons/FruitsVegeies/icons8-paprika-48.png
    - images/icons/FruitsVegeies/icons8-pear-48.png
    - images/icons/FruitsVegeies/icons8-peas-48.png
    - images/icons/FruitsVegeies/icons8-pineapple-48.png
    - images/icons/FruitsVegeies/icons8-pomegranate-48.png
    - images/icons/FruitsVegeies/icons8-potato-48.png
    - images/icons/FruitsVegeies/icons8-sweet-potato-48.png
    - images/icons/FruitsVegeies/icons8-tomato-48.png
    - images/icons/FruitsVegeies/icons8-watermelon-48.png
    - images/icons/FruitsVegeies/icons8-whole-apple-48.png
    - images/icons/FruitsVegeies/icons8-zucchini-48.png
    - images/icons/Grains/icons8-flour-in-paper-packaging-48.png
    - images/icons/Grains/icons8-rolled-oats-48.png
    - images/icons/MeatFish/icons8-crab-48.png
    - images/icons/MeatFish/icons8-fish-food-48.png
    - images/icons/MeatFish/icons8-meat-64.png
    - images/icons/MeatFish/icons8-poultry-leg-48.png
    - images/icons/MeatFish/icons8-prawn-48.png
    - images/icons/MeatFish/icons8-thanksgiving-turkey-64.png
    - images/icons/Spices/icons8-salt-shaker-48.png
    - images/icons/Spices/icons8-spice-50.png 
    - images/icons/moshtryate.png   
    - images/icons/basket2.png  
    - images/icons/basket1.png
    - images/icons/add.png
    - images/icons/minus.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vibes
      fonts:
        - asset: fonts/Vibes-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
